#
#
#
# Project settings
#
#
#

project:
  output-dir: output
  render:
    - pages
  resources:
    - public/icons

revealjs-plugins:
  - attribution

filters:
  - lightbox
  - latex-environment
  - filters.lua

lightbox: auto

commands: [hl]

execute:
  # include: false
  echo: false
  output: false
  enabled: true
  # cache: true
  # freeze: auto

#
#
#
# Shared document settings
#
#
#

bibliography:
  - references.json
  # - extra-references.json

colorlinks: true
number-sections: true

crossref:
  thm-prefix: "RQ"
  thm-title: "Research Question"

mermaid:
  theme: neutral

format:
  main-html:
    output-file: digital
  main-pdf:
    output-file: print
    include-before-body:
      text: |
        \ifdefined\thetheorem
          \renewcommand{\thetheorem}{\arabic{theorem}}
        \else
        \fi
